name: Tripgame
version: ${project.version}
main: net.nimrod.tripgame.Tripgame
api-version: 1.20
description: Minecraft minigame CONTROL/BEDWARS/TOWER DEFENSE/TDM
author: Huzza27
commands:
  zone:
    description: sets a zone
    usage: /zone [set|remove]
  player:
    description: manages player list
    usage: /player [add|remove|list]
